/* BuilderPro website traffic snippet.

     <script async src="https://builderpro-os.com/embed/track.js?u=OWNER_ID"></script>

   Pasted into the <head> of the contractor's own site (Marketing -> Website in
   the portal hands it out). Records, for that owner only:
     pageview      path, title, referring host, UTM tags
     time          seconds the page was actually visible
     tool_open     a BuilderPro calculator / health / damage check loaded in the page
     tool_done     a check was completed
     lead          a tool sent a lead
     call_click    a tel: link was tapped
     email_click   a mailto: link was tapped
     form_submit   any form on the page was sent (no field values, ever)
   No cookies, no fingerprinting, no personal data. The session id lives in
   sessionStorage and dies with the tab. Country is guessed from the browser's
   time zone / language, never from an IP.

   Written by hand (not generated by tools/build-*.py). Events go in small
   batches to the site-track edge function. */
(function () {
  'use strict';
  if (window.__bpTrack) return;
  var me = document.currentScript || (function () {
    var s = document.getElementsByTagName('script');
    for (var i = s.length - 1; i >= 0; i--) if (/\/track\.js(\?|$)/.test(s[i].src || '')) return s[i];
    return null;
  })();
  var src = (me && me.src) || '';
  var m = src.match(/[?&]u=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i);
  if (!m) return;
  var OWN = m[1].toLowerCase();
  var EP = (me && me.getAttribute('data-endpoint')) || 'https://ttzwzouhiwdwamuimhpo.supabase.co/functions/v1/site-track';
  window.__bpTrack = 1;

  /* where BuilderPro tools are served from: their postMessages are trusted */
  var TOOL_ORIGINS = ['https://builderpro-os.com', 'https://www.builderpro-os.com'];
  try { TOOL_ORIGINS.push(new URL(src, location.href).origin); } catch (e) {}

  function rid() {
    var a = '', c = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    try { var b = new Uint8Array(20); crypto.getRandomValues(b); for (var i = 0; i < b.length; i++) a += c[b[i] % c.length]; return a; }
    catch (e) { for (var j = 0; j < 20; j++) a += c[Math.floor(Math.random() * c.length)]; return a; }
  }
  var SID;
  try { SID = sessionStorage.getItem('bp_sid'); if (!SID) { SID = rid(); sessionStorage.setItem('bp_sid', SID); } } catch (e) { SID = rid(); }

  function device() {
    var ua = navigator.userAgent || '';
    if (/iPad|Tablet|PlayBook|Silk/i.test(ua) || (/Android/i.test(ua) && !/Mobile/i.test(ua))) return 'tablet';
    if (/Mobi|iPhone|iPod|Android|IEMobile|Opera Mini/i.test(ua)) return 'mobile';
    return 'desktop';
  }
  /* country, roughly: the time zone first (it follows the device, not the
     language setting), then the region in the browser's locale */
  var TZ = {
    'America/New_York': 'US', 'America/Chicago': 'US', 'America/Denver': 'US', 'America/Los_Angeles': 'US', 'America/Phoenix': 'US',
    'America/Anchorage': 'US', 'Pacific/Honolulu': 'US', 'America/Detroit': 'US', 'America/Boise': 'US', 'America/Indiana/Indianapolis': 'US',
    'America/Kentucky/Louisville': 'US', 'America/Juneau': 'US', 'America/Puerto_Rico': 'PR',
    'America/Toronto': 'CA', 'America/Vancouver': 'CA', 'America/Edmonton': 'CA', 'America/Winnipeg': 'CA', 'America/Halifax': 'CA', 'America/St_Johns': 'CA', 'America/Regina': 'CA',
    'America/Mexico_City': 'MX', 'America/Monterrey': 'MX', 'America/Tijuana': 'MX', 'America/Cancun': 'MX',
    'Europe/London': 'GB', 'Europe/Dublin': 'IE', 'Europe/Paris': 'FR', 'Europe/Berlin': 'DE', 'Europe/Madrid': 'ES', 'Europe/Rome': 'IT',
    'Europe/Amsterdam': 'NL', 'Europe/Brussels': 'BE', 'Europe/Zurich': 'CH', 'Europe/Vienna': 'AT', 'Europe/Stockholm': 'SE', 'Europe/Oslo': 'NO',
    'Europe/Copenhagen': 'DK', 'Europe/Warsaw': 'PL', 'Europe/Lisbon': 'PT', 'Asia/Yerevan': 'AM', 'Australia/Sydney': 'AU', 'Australia/Melbourne': 'AU',
    'Australia/Brisbane': 'AU', 'Australia/Perth': 'AU', 'Pacific/Auckland': 'NZ', 'Asia/Kolkata': 'IN', 'Asia/Dubai': 'AE', 'Asia/Tokyo': 'JP'
  };
  function country() {
    var tz = '';
    try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone || ''; } catch (e) {}
    if (TZ[tz]) return TZ[tz];
    var l = (navigator.languages && navigator.languages[0]) || navigator.language || '';
    var r = l.split('-')[1];
    return r && /^[a-z]{2}$/i.test(r) ? r.toUpperCase() : '';
  }
  var DEV = device(), CC = country();

  function qp(k) { try { return new URLSearchParams(location.search).get(k) || ''; } catch (e) { return ''; } }
  var UTM = { us: qp('utm_source'), um: qp('utm_medium'), uc: qp('utm_campaign') };
  /* the referring site, as a host, and only when it is someone else's */
  function refHost() {
    try {
      if (!document.referrer) return '';
      var h = new URL(document.referrer).hostname;
      return h && h !== location.hostname ? h : '';
    } catch (e) { return ''; }
  }

  var Q = [], timer = null;
  function payload() { return JSON.stringify({ u: OWN, s: SID, d: DEV, c: CC, e: Q.splice(0, 25) }); }
  function flush(beacon) {
    clearTimeout(timer); timer = null;
    while (Q.length) {
      var body = payload();
      var sent = false;
      if (beacon && navigator.sendBeacon) {
        try { sent = navigator.sendBeacon(EP, new Blob([body], { type: 'text/plain' })); } catch (e) {}
      }
      if (!sent) {
        try { fetch(EP, { method: 'POST', body: body, keepalive: true, headers: { 'Content-Type': 'text/plain' }, mode: 'cors', credentials: 'omit' }).catch(function () {}); } catch (e) {}
      }
    }
  }
  function track(type, value, now) {
    Q.push({ t: type, ts: Date.now(), p: location.pathname, ti: (document.title || '').slice(0, 160),
      r: refHost(), us: UTM.us, um: UTM.um, uc: UTM.uc, v: value || {} });
    if (now || Q.length >= 10) flush(false);
    else if (!timer) timer = setTimeout(function () { flush(false); }, 4000);
  }
  window.bpTrack = function (name, value) { track('custom', { name: String(name || '').slice(0, 40), v: value == null ? '' : value }); };

  /* page view, sent at once so a bounce is still counted */
  track(qp('bp_verify') ? 'verify' : 'pageview', {}, true);

  /* time on page: only while the page is actually visible */
  var shown = document.visibilityState !== 'hidden' ? Date.now() : 0, seen = 0, timeSent = false;
  function stopClock() { if (shown) { seen += Date.now() - shown; shown = 0; } }
  function sendTime() {
    stopClock();
    var sec = Math.round(seen / 1000);
    if (!timeSent && sec > 0) { timeSent = true; track('time', { sec: Math.min(sec, 3600) }); }
    flush(true);
  }
  document.addEventListener('visibilitychange', function () {
    if (document.visibilityState === 'hidden') sendTime();
    else { shown = Date.now(); timeSent = false; seen = 0; }
  });
  window.addEventListener('pagehide', sendTime);

  /* calls and emails: the conversions a contractor's site mostly exists for */
  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
    if (!a) return;
    var h = (a.getAttribute('href') || '').trim().toLowerCase();
    if (h.indexOf('tel:') === 0) track('call_click', {}, true);
    else if (h.indexOf('mailto:') === 0) track('email_click', {}, true);
  }, true);

  /* a form was sent — which form, never what was in it */
  document.addEventListener('submit', function (e) {
    var f = e.target, id = '';
    try { id = (f.getAttribute('id') || f.getAttribute('name') || '').slice(0, 40); } catch (x) {}
    track('form_submit', id ? { form: id } : {}, true);
  }, true);

  /* the BuilderPro tools embedded in the page say when they open, finish and send a lead */
  var opened = {};
  window.addEventListener('message', function (e) {
    var d = e && e.data;
    if (!d || typeof d !== 'object' || typeof d.bp !== 'string') return;
    var o = e.origin === 'null' ? 'file://' : e.origin; /* local files report either spelling */
    if (TOOL_ORIGINS.indexOf(o) < 0) return;
    var tool = String(d.tool || '').slice(0, 20), v = { tool: tool };
    if (d.trade) v.trade = String(d.trade).slice(0, 20);
    if (d.bp === 'bp:tool-open') {
      var k = tool + ':' + (d.id || d.trade || '');
      if (opened[k]) return; opened[k] = 1;
      track('tool_open', v);
    } else if (d.bp === 'bp:tool-done') track('tool_done', v);
    else if (d.bp === 'bp:lead') track('lead', v, true);
  });
})();
