/* ==================================================================
   The built-in materials catalog: what a contractor buys, and who sells it.

   Ordering used to start from nothing. A brand new account had no price
   book, so the search box had nothing to search and the first screen was
   a chore ("photograph a bill") standing between the contractor and the
   thing they came to do. This is the catalog that ships with the product,
   so search works on day one, for every trade we support.

   Each row knows WHICH CHAINS CARRY IT. That mapping is the useful part
   and it is stable: roofing distributors carry shingles, Ferguson carries
   pipe, SiteOne carries irrigation, and the big boxes carry the gap fill.
   The chain ids here are the ones in supply-dir.js, so "who sells this"
   and "add them as a supplier" are the same list.

   WHAT THIS IS NOT, said plainly because the page says it too: this is
   not a live feed of Home Depot or Lowe's pricing. There is no public
   catalogue API for either, prices are per-store and move weekly, and
   scraping them would be both against their terms and wrong within a
   month. So a price here is a TYPICAL price — a ballpark, labelled as
   one, good enough to size a job. The moment a contractor adds their own
   supplier, their real negotiated price replaces it everywhere, and that
   is the number we order and cost the job with.

   Three tiers, never blurred together in the UI:
     yours     from your own paperwork or price book. Exact. Used to order.
     typical   from this table. A ballpark. Never used as a real cost.
     none      nobody has priced it. The supplier quotes it (TBC).

   Extends window.SP from supply.js.
   ================================================================== */
(function () {
  'use strict';
  var SP = window.SP; if (!SP) return;

  /* Shorthands for the usual sets, so a row stays readable. These expand
     to the chain ids in supply-dir.js. */
  var G = {
    box:   'homedepot_pro lowes_pro menards',
    roof:  'abc srs beacon',
    plumb: 'ferguson winsupply supplyhouse',
    elec:  'ced graybar winsupply',
    hvac:  'johnstone ferguson supplyhouse',
    paint: 'sherwin benmoore',
    land:  'siteone srs',
    conc:  'whitecap',
    dry:   'lw fbm',
    lum:   'bfs e84 carter',
    tool:  'fastenal grainger zoro',
    pool:  'poolcorp heritagepool leslies',
    tile:  'floordecor tileshop msi',
    stone: 'msi cosentino floordecor',
    cab:   'richelieu homedepot_pro lowes_pro',
    mill:  'metrie bfs carter e84',
  };
  function carriers(s) {
    var out = [];
    String(s || '').split(/\s+/).forEach(function (t) {
      if (!t) return;
      (G[t] ? G[t].split(' ') : [t]).forEach(function (x) { if (out.indexOf(x) < 0) out.push(x); });
    });
    return out;
  }

  var C = [];
  /* row: [name, category, unit, typical low, typical high, who carries it] */
  function add(trade, rows) {
    rows.forEach(function (r) {
      C.push({ name: r[0], cat: r[1], unit: r[2], lo: r[3], hi: r[4], car: carriers(r[5]), trade: trade });
    });
  }

  add('roofing', [
    ['Architectural shingles, 30-year, bundle', 'Shingles', 'bundle', 34, 46, 'roof box'],
    ['Architectural shingles, 50-year, bundle', 'Shingles', 'bundle', 44, 58, 'roof'],
    ['3-tab shingles, 25-year, bundle', 'Shingles', 'bundle', 28, 38, 'roof box'],
    ['Designer shingles, bundle', 'Shingles', 'bundle', 58, 82, 'roof'],
    ['Ridge cap shingles, 20 lf bundle', 'Shingles', 'bundle', 48, 66, 'roof box'],
    ['Starter strip shingles, 100 lf bundle', 'Shingles', 'bundle', 36, 52, 'roof box'],
    ['Hip and ridge, high profile, bundle', 'Shingles', 'bundle', 62, 88, 'roof'],
    ['Synthetic underlayment, 10 sq roll', 'Underlayment', 'roll', 68, 105, 'roof box'],
    ['Felt underlayment 15 lb, 4 sq roll', 'Underlayment', 'roll', 24, 34, 'roof box'],
    ['Felt underlayment 30 lb, 2 sq roll', 'Underlayment', 'roll', 26, 38, 'roof box'],
    ['Ice and water shield, 2 sq roll', 'Underlayment', 'roll', 82, 120, 'roof box'],
    ['Ice and water shield, high temp, 2 sq', 'Underlayment', 'roll', 115, 165, 'roof'],
    ['Aluminum drip edge, 10 ft', 'Metal', 'ea', 7.5, 13, 'roof box'],
    ['Galvanized drip edge, 10 ft', 'Metal', 'ea', 8, 14, 'roof box'],
    ['Valley metal, W-style, 10 ft', 'Metal', 'ea', 20, 32, 'roof'],
    ['Flashing coil, aluminum, 50 ft', 'Metal', 'roll', 115, 175, 'roof'],
    ['Step flashing 4x4x8, 100 ct', 'Flashing', 'box', 38, 58, 'roof box'],
    ['Pipe boot flashing, 3 in', 'Flashing', 'ea', 9.5, 17, 'roof box'],
    ['Pipe boot flashing, lead, 3 in', 'Flashing', 'ea', 22, 38, 'roof'],
    ['Chimney flashing kit', 'Flashing', 'ea', 58, 110, 'roof'],
    ['Counter flashing, 10 ft', 'Flashing', 'ea', 16, 28, 'roof'],
    ['Roofing nails 1-1/4 in, 30 lb', 'Fasteners', 'box', 52, 78, 'roof box'],
    ['Roofing nails 1-1/2 in, 30 lb', 'Fasteners', 'box', 54, 82, 'roof box'],
    ['Cap nails 1 in, 3000 ct', 'Fasteners', 'box', 42, 68, 'roof box'],
    ['Plastic cap staples, 2000 ct', 'Fasteners', 'box', 22, 36, 'roof'],
    ['Ridge vent, 4 ft section', 'Ventilation', 'ea', 14, 24, 'roof box'],
    ['Ridge vent, 20 ft roll', 'Ventilation', 'roll', 62, 98, 'roof box'],
    ['Soffit vent, 8 ft strip', 'Ventilation', 'ea', 9, 16, 'roof box'],
    ['Box vent, 50 sq in', 'Ventilation', 'ea', 16, 28, 'roof box'],
    ['Turbine vent, 12 in', 'Ventilation', 'ea', 42, 72, 'roof box'],
    ['Roof cement, 10 oz tube', 'Sealants', 'ea', 4.5, 8.5, 'roof box'],
    ['Roof cement, 5 gal', 'Sealants', 'ea', 52, 88, 'roof box'],
    ['Polyurethane sealant, 10 oz', 'Sealants', 'ea', 7, 13, 'roof box'],
    ['Butyl seam tape, 4 in x 50 ft', 'Sealants', 'roll', 28, 48, 'roof'],
    ['Standing seam panel, 16 in, per lf', 'Metal', 'lf', 4.5, 9, 'roof'],
    ['Exposed fastener panel, 3 ft, per lf', 'Metal', 'lf', 2.4, 4.6, 'roof box'],
    ['Metal roof screws with washer, 250 ct', 'Fasteners', 'box', 28, 48, 'roof box'],
    ['Foam closure strips, 10 ft', 'Sealants', 'ea', 6, 12, 'roof'],
    ['TPO membrane 60 mil, 10 sq roll', 'Underlayment', 'roll', 285, 420, 'roof'],
    ['EPDM membrane 45 mil, 10 sq roll', 'Underlayment', 'roll', 245, 380, 'roof'],
    ['Polyiso insulation board 2 in, 4x8', 'Underlayment', 'ea', 38, 62, 'roof dry'],
    ['Bonding adhesive, 5 gal', 'Sealants', 'ea', 145, 225, 'roof'],
    ['Gutter, 5 in K-style, 10 ft', 'Metal', 'ea', 11, 19, 'roof box'],
    ['Gutter, 6 in K-style, 10 ft', 'Metal', 'ea', 15, 26, 'roof box'],
    ['Downspout, 2x3, 10 ft', 'Metal', 'ea', 10, 17, 'roof box'],
    ['Downspout elbow, 2x3', 'Metal', 'ea', 4, 8, 'roof box'],
    ['Hidden gutter hangers, 25 ct', 'Hardware', 'box', 38, 62, 'roof box'],
    ['Gutter guard, 4 ft section', 'Metal', 'ea', 7, 16, 'roof box'],
    ['Snow guards, 10 ct', 'Hardware', 'box', 68, 130, 'roof'],
    ['Roof harness and anchor kit', 'Tools', 'ea', 95, 185, 'roof box tool'],
    ['Magnetic nail sweeper, 24 in', 'Tools', 'ea', 58, 105, 'roof box tool'],
    ['Hook blades, 100 ct', 'Tools', 'box', 16, 30, 'roof box'],
  ]);

  add('plumbing', [
    ['PEX-A 1/2 in, 100 ft coil', 'Pipe', 'roll', 42, 68, 'plumb box pexuniverse'],
    ['PEX-A 3/4 in, 100 ft coil', 'Pipe', 'roll', 72, 110, 'plumb box pexuniverse'],
    ['PEX-B 1/2 in, 100 ft coil', 'Pipe', 'roll', 32, 52, 'plumb box'],
    ['PEX-B 3/4 in, 100 ft coil', 'Pipe', 'roll', 58, 92, 'plumb box'],
    ['Copper type L 1/2 in, 10 ft', 'Pipe', 'ea', 22, 38, 'plumb box'],
    ['Copper type L 3/4 in, 10 ft', 'Pipe', 'ea', 36, 58, 'plumb box'],
    ['Copper type M 1/2 in, 10 ft', 'Pipe', 'ea', 18, 30, 'plumb box'],
    ['PVC sch 40, 2 in, 10 ft', 'Pipe', 'ea', 11, 19, 'plumb box'],
    ['PVC sch 40, 3 in, 10 ft', 'Pipe', 'ea', 19, 32, 'plumb box'],
    ['PVC sch 40, 4 in, 10 ft', 'Pipe', 'ea', 26, 44, 'plumb box'],
    ['ABS DWV 2 in, 10 ft', 'Pipe', 'ea', 12, 21, 'plumb box'],
    ['CPVC 3/4 in, 10 ft', 'Pipe', 'ea', 9, 16, 'plumb box'],
    ['Cast iron no-hub 4 in, 10 ft', 'Pipe', 'ea', 78, 135, 'plumb'],
    ['PEX expansion fitting, 1/2 elbow, 10 pk', 'Fittings', 'bag', 24, 42, 'plumb pexuniverse'],
    ['PEX expansion fitting, 3/4 elbow, 10 pk', 'Fittings', 'bag', 28, 48, 'plumb pexuniverse'],
    ['PEX crimp rings 1/2 in, 100 ct', 'Fittings', 'bag', 14, 26, 'plumb box'],
    ['Push-to-connect coupling 1/2 in', 'Fittings', 'ea', 6.5, 12, 'plumb box'],
    ['Push-to-connect elbow 3/4 in', 'Fittings', 'ea', 9, 16, 'plumb box'],
    ['Copper 90 elbow 1/2 in, 10 pk', 'Fittings', 'bag', 8, 16, 'plumb box'],
    ['Copper tee 3/4 in, 10 pk', 'Fittings', 'bag', 18, 34, 'plumb box'],
    ['PVC 90 elbow 2 in', 'Fittings', 'ea', 2.6, 5, 'plumb box'],
    ['PVC sanitary tee 3 in', 'Fittings', 'ea', 7, 13, 'plumb box'],
    ['Closet flange, PVC 4x3', 'Fittings', 'ea', 8, 15, 'plumb box'],
    ['Supply line 3/8 x 12 in braided', 'Fittings', 'ea', 6, 12, 'plumb box'],
    ['Supply line 3/8 x 20 in braided', 'Fittings', 'ea', 7, 14, 'plumb box'],
    ['Ball valve 1/2 in', 'Valves', 'ea', 10, 19, 'plumb box'],
    ['Ball valve 3/4 in', 'Valves', 'ea', 13, 24, 'plumb box'],
    ['Gate valve 3/4 in', 'Valves', 'ea', 16, 30, 'plumb box'],
    ['Angle stop 1/2 x 3/8', 'Valves', 'ea', 7, 14, 'plumb box'],
    ['Pressure reducing valve 3/4 in', 'Valves', 'ea', 68, 125, 'plumb box'],
    ['Backflow preventer 3/4 in', 'Valves', 'ea', 95, 185, 'plumb'],
    ['Hose bibb, frost free 12 in', 'Valves', 'ea', 24, 44, 'plumb box'],
    ['Thermal expansion tank, 2 gal', 'Equipment', 'ea', 38, 68, 'plumb box'],
    ['Water heater, 40 gal gas', 'Equipment', 'ea', 620, 1050, 'plumb box'],
    ['Water heater, 50 gal gas', 'Equipment', 'ea', 750, 1250, 'plumb box'],
    ['Water heater, 50 gal electric', 'Equipment', 'ea', 580, 980, 'plumb box'],
    ['Tankless water heater, gas', 'Equipment', 'ea', 950, 1750, 'plumb box'],
    ['Sump pump, 1/3 HP', 'Equipment', 'ea', 130, 240, 'plumb box'],
    ['Sewage ejector pump', 'Equipment', 'ea', 340, 620, 'plumb'],
    ['Water softener, 40k grain', 'Equipment', 'ea', 480, 850, 'plumb box'],
    ['Recirculation pump', 'Equipment', 'ea', 180, 340, 'plumb supplyhouse'],
    ['P-trap 1-1/2 in PVC', 'Drainage', 'ea', 5, 10, 'plumb box'],
    ['Floor drain, 3 in', 'Drainage', 'ea', 34, 62, 'plumb box'],
    ['Cleanout plug and adapter, 4 in', 'Drainage', 'ea', 9, 17, 'plumb box'],
    ['Condensate pump', 'Drainage', 'ea', 52, 95, 'plumb hvac'],
    ['Toilet, two piece elongated', 'Fixtures', 'ea', 165, 380, 'plumb box'],
    ['Toilet, one piece', 'Fixtures', 'ea', 320, 680, 'plumb box'],
    ['Wax ring with flange', 'Fixtures', 'ea', 4, 9, 'plumb box'],
    ['Lavatory faucet, single hole', 'Fixtures', 'ea', 78, 210, 'plumb box'],
    ['Kitchen faucet, pull down', 'Fixtures', 'ea', 140, 390, 'plumb box'],
    ['Shower valve, pressure balance', 'Fixtures', 'ea', 95, 220, 'plumb box'],
    ['Tub spout and trim kit', 'Fixtures', 'ea', 68, 180, 'plumb box'],
    ['Stainless undermount sink, 16 ga', 'Fixtures', 'ea', 185, 420, 'plumb box'],
    ['Garbage disposal, 3/4 HP', 'Fixtures', 'ea', 130, 265, 'plumb box'],
    ['Lead-free solder, 1 lb', 'Sealants', 'ea', 24, 42, 'plumb box'],
    ['Soldering flux, 4 oz', 'Sealants', 'ea', 6, 12, 'plumb box'],
    ['PVC cement and primer set', 'Sealants', 'ea', 12, 22, 'plumb box'],
    ['Teflon tape, 10 pk', 'Sealants', 'pk', 8, 16, 'plumb box'],
    ['Pipe insulation 3/4 in, 6 ft', 'Prep', 'ea', 2.2, 4.5, 'plumb box'],
  ]);

  add('electrical', [
    ['Romex NM-B 14/2, 250 ft', 'Wire', 'roll', 62, 105, 'elec box'],
    ['Romex NM-B 12/2, 250 ft', 'Wire', 'roll', 88, 145, 'elec box'],
    ['Romex NM-B 12/3, 250 ft', 'Wire', 'roll', 135, 215, 'elec box'],
    ['Romex NM-B 10/2, 250 ft', 'Wire', 'roll', 145, 235, 'elec box'],
    ['Romex NM-B 10/3, 250 ft', 'Wire', 'roll', 195, 310, 'elec box'],
    ['Romex NM-B 6/3, 125 ft', 'Wire', 'roll', 280, 450, 'elec box'],
    ['THHN 12 AWG, 500 ft', 'Wire', 'roll', 62, 105, 'elec box'],
    ['THHN 10 AWG, 500 ft', 'Wire', 'roll', 95, 160, 'elec box'],
    ['UF-B 12/2 direct burial, 250 ft', 'Wire', 'roll', 130, 210, 'elec box'],
    ['SER 4/0 aluminum, per ft', 'Wire', 'lf', 4.2, 7.5, 'elec'],
    ['Bare copper ground 6 AWG, 100 ft', 'Wire', 'roll', 58, 95, 'elec box'],
    ['Breaker 15A single pole', 'Breakers', 'ea', 6.5, 13, 'elec box'],
    ['Breaker 20A single pole', 'Breakers', 'ea', 7, 14, 'elec box'],
    ['Breaker 30A double pole', 'Breakers', 'ea', 15, 28, 'elec box'],
    ['Breaker 50A double pole', 'Breakers', 'ea', 18, 34, 'elec box'],
    ['AFCI breaker 20A', 'Breakers', 'ea', 42, 72, 'elec box'],
    ['GFCI breaker 20A', 'Breakers', 'ea', 48, 85, 'elec box'],
    ['Load center 100A, 20 space', 'Panels', 'ea', 95, 175, 'elec box'],
    ['Load center 200A, 40 space', 'Panels', 'ea', 195, 340, 'elec box'],
    ['Meter main combo 200A', 'Panels', 'ea', 280, 520, 'elec'],
    ['Generator interlock kit', 'Panels', 'ea', 58, 110, 'elec box'],
    ['Transfer switch, 10 circuit', 'Panels', 'ea', 280, 480, 'elec box'],
    ['Duplex receptacle 15A TR, 10 pk', 'Devices', 'box', 16, 30, 'elec box'],
    ['Duplex receptacle 20A TR, 10 pk', 'Devices', 'box', 26, 46, 'elec box'],
    ['GFCI receptacle 20A', 'Devices', 'ea', 17, 30, 'elec box'],
    ['USB receptacle 20A', 'Devices', 'ea', 28, 52, 'elec box'],
    ['Decora switch single pole, 10 pk', 'Devices', 'box', 22, 40, 'elec box'],
    ['Three way switch, 10 pk', 'Devices', 'box', 32, 58, 'elec box'],
    ['Dimmer switch, LED compatible', 'Devices', 'ea', 18, 34, 'elec box'],
    ['Smart switch, wifi', 'Devices', 'ea', 28, 55, 'elec box'],
    ['Wall plate, white, 10 pk', 'Devices', 'box', 8, 16, 'elec box'],
    ['Single gang old work box, 25 pk', 'Boxes', 'box', 26, 46, 'elec box'],
    ['Single gang new work box, 25 pk', 'Boxes', 'box', 16, 30, 'elec box'],
    ['Double gang box, 10 pk', 'Boxes', 'box', 18, 34, 'elec box'],
    ['4 in square box with mud ring', 'Boxes', 'ea', 4.5, 9, 'elec box'],
    ['Ceiling fan rated box', 'Boxes', 'ea', 8, 16, 'elec box'],
    ['Weatherproof box and cover', 'Boxes', 'ea', 11, 22, 'elec box'],
    ['EMT 1/2 in, 10 ft', 'Conduit', 'ea', 7, 13, 'elec box'],
    ['EMT 3/4 in, 10 ft', 'Conduit', 'ea', 8.5, 16, 'elec box'],
    ['PVC conduit sch 40, 3/4 in, 10 ft', 'Conduit', 'ea', 5, 10, 'elec box'],
    ['Liquidtight flex 3/4 in, 25 ft', 'Conduit', 'roll', 42, 75, 'elec box'],
    ['EMT connectors 3/4 in, 25 pk', 'Conduit', 'box', 18, 34, 'elec box'],
    ['Conduit straps 3/4 in, 100 ct', 'Conduit', 'box', 14, 26, 'elec box'],
    ['Wire nuts assorted, 100 ct', 'Connectors', 'box', 10, 20, 'elec box'],
    ['Push-in connectors 3 port, 100 ct', 'Connectors', 'box', 26, 46, 'elec box'],
    ['NM cable connectors, 50 ct', 'Connectors', 'box', 16, 30, 'elec box'],
    ['Ground bar kit', 'Connectors', 'ea', 9, 18, 'elec box'],
    ['LED recessed 6 in, 4 pk', 'Lighting', 'case', 42, 78, 'elec box'],
    ['LED recessed 4 in, 4 pk', 'Lighting', 'case', 38, 70, 'elec box'],
    ['LED wafer light 6 in', 'Lighting', 'ea', 11, 22, 'elec box'],
    ['LED shop light 4 ft', 'Lighting', 'ea', 24, 48, 'elec box'],
    ['LED flood light, 50W', 'Lighting', 'ea', 32, 62, 'elec box'],
    ['Under cabinet LED, 24 in', 'Lighting', 'ea', 26, 52, 'elec box'],
    ['Exhaust fan, 110 CFM', 'Equipment', 'ea', 68, 130, 'elec box'],
    ['Ceiling fan, 52 in', 'Equipment', 'ea', 95, 240, 'elec box'],
    ['Smoke and CO detector, hardwired', 'Devices', 'ea', 34, 62, 'elec box'],
    ['Ground rod 8 ft copper clad', 'Hardware', 'ea', 18, 32, 'elec box'],
    ['EV charger, 48A', 'Equipment', 'ea', 400, 750, 'elec box'],
  ]);

  add('hvac', [
    ['R-410A refrigerant, 25 lb', 'Refrigerant', 'cyl', 185, 320, 'hvac'],
    ['R-454B refrigerant, 25 lb', 'Refrigerant', 'cyl', 240, 420, 'hvac'],
    ['Line set 3/8 x 3/4, 50 ft', 'Copper', 'ea', 165, 275, 'hvac box'],
    ['Line set 1/4 x 1/2, 25 ft', 'Copper', 'ea', 78, 135, 'hvac box'],
    ['Copper coil 3/8 in, 50 ft', 'Copper', 'roll', 95, 165, 'hvac plumb'],
    ['Condenser 2.5 ton, 14 SEER', 'Equipment', 'ea', 1250, 2100, 'hvac hvacdirect'],
    ['Condenser 3 ton, 16 SEER', 'Equipment', 'ea', 1650, 2800, 'hvac hvacdirect'],
    ['Air handler 3 ton', 'Equipment', 'ea', 950, 1700, 'hvac hvacdirect'],
    ['Gas furnace 80k BTU, 80%', 'Equipment', 'ea', 850, 1550, 'hvac hvacdirect'],
    ['Gas furnace 100k BTU, 96%', 'Equipment', 'ea', 1450, 2500, 'hvac hvacdirect'],
    ['Mini split 12k BTU, single zone', 'Equipment', 'ea', 850, 1500, 'hvac hvacdirect supplyhouse'],
    ['Evaporator coil, cased 3 ton', 'Equipment', 'ea', 520, 920, 'hvac'],
    ['Heat pump 3 ton', 'Equipment', 'ea', 1850, 3200, 'hvac hvacdirect'],
    ['Run capacitor 45/5 MFD', 'Electrical', 'ea', 16, 32, 'hvac box'],
    ['Run capacitor 35/5 MFD', 'Electrical', 'ea', 14, 28, 'hvac box'],
    ['Contactor 2 pole 30A', 'Electrical', 'ea', 14, 28, 'hvac box'],
    ['Hard start kit', 'Electrical', 'ea', 24, 48, 'hvac'],
    ['Disconnect box 60A, non-fused', 'Electrical', 'ea', 18, 36, 'hvac elec box'],
    ['Whip, 6 ft 10/2', 'Electrical', 'ea', 22, 42, 'hvac elec box'],
    ['Transformer 40 VA', 'Electrical', 'ea', 18, 34, 'hvac'],
    ['Smart thermostat', 'Controls', 'ea', 95, 250, 'hvac box'],
    ['Programmable thermostat', 'Controls', 'ea', 34, 78, 'hvac box'],
    ['Zone control board, 3 zone', 'Controls', 'ea', 240, 420, 'hvac'],
    ['Zone damper, 8 in', 'Controls', 'ea', 68, 125, 'hvac'],
    ['Condensate float switch', 'Controls', 'ea', 11, 22, 'hvac'],
    ['Pleated filter 16x25x1, 12 pk', 'Filters', 'case', 38, 68, 'hvac box'],
    ['Pleated filter 20x25x1, 12 pk', 'Filters', 'case', 42, 78, 'hvac box'],
    ['Media filter 20x25x5', 'Filters', 'ea', 34, 65, 'hvac box'],
    ['Blower motor 1/2 HP, ECM', 'Motors', 'ea', 280, 520, 'hvac'],
    ['Condenser fan motor 1/4 HP', 'Motors', 'ea', 95, 180, 'hvac'],
    ['Inducer motor assembly', 'Motors', 'ea', 185, 340, 'hvac'],
    ['Flex duct R8, 8 in x 25 ft', 'Duct', 'ea', 48, 88, 'hvac box'],
    ['Flex duct R8, 6 in x 25 ft', 'Duct', 'ea', 38, 72, 'hvac box'],
    ['Rigid duct 8 in, 5 ft', 'Duct', 'ea', 14, 26, 'hvac box'],
    ['Sheet metal plenum, 20x20x48', 'Duct', 'ea', 78, 145, 'hvac'],
    ['Supply register 4x10', 'Duct', 'ea', 8, 18, 'hvac box'],
    ['Return grille 20x20', 'Duct', 'ea', 24, 48, 'hvac box'],
    ['Duct board 1-1/2 in, 4x10', 'Duct', 'ea', 42, 78, 'hvac'],
    ['Foil duct tape, 2 in x 60 yd', 'Sealants', 'roll', 9, 18, 'hvac box'],
    ['Duct mastic, 1 gal', 'Sealants', 'ea', 18, 34, 'hvac box'],
    ['Nitrogen regulator', 'Tools', 'ea', 120, 240, 'hvac'],
    ['Equipment pad 36x36', 'Install', 'ea', 52, 98, 'hvac box'],
    ['Line set cover kit', 'Install', 'ea', 42, 85, 'hvac supplyhouse'],
    ['Condensate pump, 120V', 'Drainage', 'ea', 48, 92, 'hvac plumb'],
    ['UV air purifier', 'Equipment', 'ea', 240, 450, 'hvac'],
    ['Whole house humidifier', 'Equipment', 'ea', 180, 340, 'hvac box'],
  ]);

  add('painting', [
    ['Interior paint, eggshell, 5 gal', 'Paint', 'ea', 135, 235, 'paint box'],
    ['Interior paint, flat, 5 gal', 'Paint', 'ea', 120, 210, 'paint box'],
    ['Interior paint, satin, 5 gal', 'Paint', 'ea', 145, 250, 'paint box'],
    ['Interior paint, semi-gloss, 5 gal', 'Paint', 'ea', 150, 260, 'paint box'],
    ['Exterior paint, satin, 5 gal', 'Paint', 'ea', 175, 300, 'paint box'],
    ['Exterior paint, flat, 5 gal', 'Paint', 'ea', 165, 285, 'paint box'],
    ['Ceiling paint, flat white, 5 gal', 'Paint', 'ea', 95, 175, 'paint box'],
    ['Primer, PVA drywall, 5 gal', 'Paint', 'ea', 78, 140, 'paint box'],
    ['Primer, stain blocking oil, 5 gal', 'Paint', 'ea', 135, 235, 'paint box'],
    ['Primer, bonding, 1 gal', 'Paint', 'ea', 34, 62, 'paint box'],
    ['Cabinet enamel, 1 gal', 'Paint', 'ea', 58, 110, 'paint box'],
    ['Porch and floor enamel, 1 gal', 'Paint', 'ea', 42, 78, 'paint box'],
    ['Exterior stain, semi-transparent, 5 gal', 'Paint', 'ea', 165, 290, 'paint box'],
    ['Elastomeric coating, 5 gal', 'Paint', 'ea', 145, 265, 'paint box'],
    ['Roller cover 9 in, 3/8 nap, 6 pk', 'Tools', 'pk', 18, 34, 'paint box'],
    ['Roller cover 9 in, 1/2 nap, 6 pk', 'Tools', 'pk', 20, 38, 'paint box'],
    ['Roller cover 18 in, 3/8 nap', 'Tools', 'ea', 11, 22, 'paint box'],
    ['Roller frame 9 in', 'Tools', 'ea', 8, 16, 'paint box'],
    ['Brush 2.5 in angled sash', 'Tools', 'ea', 12, 24, 'paint box'],
    ['Brush 4 in wall', 'Tools', 'ea', 16, 32, 'paint box'],
    ['Airless spray tip, 517', 'Tools', 'ea', 22, 42, 'paint box'],
    ['Spray sock and filters', 'Tools', 'pk', 14, 28, 'paint'],
    ['5 gal bucket and grid', 'Tools', 'ea', 12, 24, 'paint box'],
    ['Painter tape 1.5 in, 6 pk', 'Prep', 'pk', 28, 48, 'paint box'],
    ['Painter tape 2 in, 6 pk', 'Prep', 'pk', 34, 58, 'paint box'],
    ['Masking film 24 in x 180 ft', 'Prep', 'roll', 14, 28, 'paint box'],
    ['Drop cloth canvas 9x12', 'Prep', 'ea', 22, 42, 'paint box'],
    ['Drop cloth plastic 9x12, 3 pk', 'Prep', 'pk', 12, 24, 'paint box'],
    ['Rosin paper 36 in x 166 ft', 'Prep', 'roll', 24, 44, 'paint box'],
    ['Sanding sponges, 12 pk', 'Prep', 'pk', 14, 26, 'paint box'],
    ['Sanding pole and screens', 'Prep', 'ea', 24, 46, 'paint box dry'],
    ['Joint compound, 4.5 gal', 'Prep', 'ea', 16, 30, 'paint box dry'],
    ['Spackling paste, 1 gal', 'Prep', 'ea', 14, 28, 'paint box'],
    ['Wood filler, 1 qt', 'Prep', 'ea', 12, 24, 'paint box'],
    ['TSP cleaner, 1 gal', 'Prep', 'ea', 14, 26, 'paint box'],
    ['Caulk, paintable acrylic, 12 pk', 'Sealants', 'case', 32, 58, 'paint box'],
    ['Caulk, siliconized acrylic, 12 pk', 'Sealants', 'case', 38, 68, 'paint box'],
    ['Exterior sealant, 10 oz', 'Sealants', 'ea', 8, 16, 'paint box'],
  ]);

  add('landscaping', [
    ['Sod, bermuda, pallet', 'Turf', 'pallet', 260, 420, 'land'],
    ['Sod, fescue, pallet', 'Turf', 'pallet', 280, 450, 'land'],
    ['Sod, zoysia, pallet', 'Turf', 'pallet', 340, 520, 'land'],
    ['Grass seed, tall fescue, 50 lb', 'Turf', 'bag', 120, 200, 'land box'],
    ['Starter fertilizer, 50 lb', 'Turf', 'bag', 38, 68, 'land box'],
    ['Weed and feed, 50 lb', 'Turf', 'bag', 42, 75, 'land box'],
    ['Mulch, hardwood, cu yd', 'Bulk', 'yd', 32, 58, 'land'],
    ['Mulch, cedar, cu yd', 'Bulk', 'yd', 42, 72, 'land'],
    ['Mulch, bagged 2 cu ft, 50 pk', 'Bulk', 'pallet', 145, 250, 'land box'],
    ['Topsoil, screened, cu yd', 'Bulk', 'yd', 28, 52, 'land'],
    ['Compost, cu yd', 'Bulk', 'yd', 34, 62, 'land'],
    ['River rock 1 in, cu yd', 'Bulk', 'yd', 85, 145, 'land'],
    ['Decomposed granite, cu yd', 'Bulk', 'yd', 52, 95, 'land'],
    ['Paver base gravel, cu yd', 'Bulk', 'yd', 32, 58, 'land conc'],
    ['Paver sand, cu yd', 'Bulk', 'yd', 38, 68, 'land conc'],
    ['Polymeric sand, 50 lb', 'Bulk', 'bag', 28, 48, 'land box'],
    ['Paver 6x9, per sq ft', 'Hardscape', 'sqft', 3.2, 6.5, 'land box'],
    ['Paver 12x12, per sq ft', 'Hardscape', 'sqft', 3.8, 7.5, 'land box'],
    ['Retaining wall block, per sq ft', 'Hardscape', 'sqft', 6, 12, 'land box'],
    ['Flagstone, per ton', 'Hardscape', 'ton', 280, 520, 'land'],
    ['Steel edging, 8 ft', 'Hardscape', 'ea', 18, 34, 'land box'],
    ['Plastic paver edging, 8 ft', 'Hardscape', 'ea', 8, 16, 'land box'],
    ['Landscape fabric 4x100 ft', 'Prep', 'roll', 34, 62, 'land box'],
    ['Weed barrier pins, 100 ct', 'Prep', 'box', 14, 26, 'land box'],
    ['Drip tubing 1/2 in, 100 ft', 'Irrigation', 'roll', 18, 34, 'land box'],
    ['Drip emitters, 100 ct', 'Irrigation', 'bag', 16, 30, 'land box'],
    ['Sprinkler head, 4 in pop-up, 25 pk', 'Irrigation', 'case', 52, 95, 'land box'],
    ['Rotor head, 4 in, 10 pk', 'Irrigation', 'case', 95, 175, 'land'],
    ['Irrigation valve 1 in', 'Irrigation', 'ea', 22, 42, 'land box'],
    ['Valve box, 10 in round', 'Irrigation', 'ea', 14, 28, 'land box'],
    ['Irrigation controller, 8 zone', 'Irrigation', 'ea', 85, 185, 'land box'],
    ['Poly pipe 1 in, 100 ft', 'Irrigation', 'roll', 28, 52, 'land box'],
    ['Backflow preventer, 1 in PVB', 'Irrigation', 'ea', 110, 200, 'land plumb'],
    ['Shrub, 3 gal', 'Plants', 'ea', 22, 45, 'land box'],
    ['Shrub, 5 gal', 'Plants', 'ea', 34, 68, 'land box'],
    ['Tree, 15 gal', 'Plants', 'ea', 95, 185, 'land'],
    ['Perennial, 1 gal', 'Plants', 'ea', 8, 18, 'land box'],
    ['Annual flats, 18 ct', 'Plants', 'flat', 22, 42, 'land box'],
    ['Landscape lighting, path light', 'Lighting', 'ea', 34, 78, 'land box'],
    ['Low voltage transformer, 300W', 'Lighting', 'ea', 130, 240, 'land box'],
    ['Low voltage cable 12/2, 100 ft', 'Wire', 'roll', 52, 95, 'land box'],
  ]);

  add('concrete', [
    ['Ready mix 3000 psi, cu yd', 'Concrete', 'yd', 145, 210, 'conc'],
    ['Ready mix 4000 psi, cu yd', 'Concrete', 'yd', 160, 235, 'conc'],
    ['Short load fee, per yd under minimum', 'Concrete', 'ea', 40, 95, 'conc'],
    ['Concrete mix 80 lb bag', 'Concrete', 'bag', 5.5, 9.5, 'conc box'],
    ['High early strength mix, 80 lb', 'Concrete', 'bag', 7.5, 13, 'conc box'],
    ['Mortar mix type S, 80 lb', 'Concrete', 'bag', 7, 12, 'conc box'],
    ['Non-shrink grout, 50 lb', 'Concrete', 'bag', 22, 40, 'conc box'],
    ['Rebar #4, 20 ft', 'Steel', 'ea', 11, 20, 'conc box'],
    ['Rebar #5, 20 ft', 'Steel', 'ea', 17, 30, 'conc box'],
    ['Rebar #3, 20 ft', 'Steel', 'ea', 7, 13, 'conc box'],
    ['Wire mesh 6x6 W1.4, 5x10 sheet', 'Steel', 'ea', 9, 17, 'conc box'],
    ['Rebar tie wire, 3.5 lb roll', 'Steel', 'ea', 9, 18, 'conc box'],
    ['Rebar chairs, 100 ct', 'Steel', 'box', 26, 48, 'conc'],
    ['Dowel bar 3/4 x 18, 25 pk', 'Steel', 'box', 58, 105, 'conc'],
    ['Form lumber 2x4x8', 'Forms', 'ea', 3.8, 7, 'conc lum box'],
    ['Form lumber 2x8x10', 'Forms', 'ea', 11, 20, 'conc lum box'],
    ['Form stakes 24 in, 25 pk', 'Forms', 'bundle', 34, 62, 'conc box'],
    ['Form stakes 36 in, 10 pk', 'Forms', 'bundle', 28, 52, 'conc'],
    ['Snap ties, 100 ct', 'Forms', 'box', 78, 145, 'conc'],
    ['Form release agent, 5 gal', 'Forms', 'ea', 42, 78, 'conc'],
    ['Expansion joint 1/2 x 4 in x 50 ft', 'Joints', 'roll', 15, 28, 'conc box'],
    ['Control joint strip, 10 ft', 'Joints', 'ea', 6, 12, 'conc'],
    ['Backer rod 1/2 in, 100 ft', 'Joints', 'roll', 9, 18, 'conc box'],
    ['Self leveling joint sealant, 10 oz', 'Joints', 'ea', 9, 17, 'conc box'],
    ['Curing compound, 5 gal', 'Finish', 'ea', 68, 125, 'conc'],
    ['Concrete sealer, 5 gal', 'Finish', 'ea', 95, 175, 'conc box'],
    ['Densifier, 5 gal', 'Finish', 'ea', 110, 195, 'conc'],
    ['Color hardener, 60 lb', 'Finish', 'bag', 48, 88, 'conc'],
    ['Release powder, 30 lb', 'Finish', 'bag', 52, 95, 'conc'],
    ['Vapor barrier 10 mil, 20x100', 'Prep', 'roll', 85, 155, 'conc box'],
    ['Vapor barrier 15 mil, 20x100', 'Prep', 'roll', 135, 240, 'conc'],
    ['Anchor bolt 1/2 x 10, 50 pk', 'Hardware', 'box', 34, 62, 'conc box'],
    ['Wedge anchor 1/2 x 4-3/4, 50 pk', 'Hardware', 'box', 58, 105, 'conc box tool'],
    ['Epoxy anchoring adhesive, tube', 'Hardware', 'ea', 24, 46, 'conc box'],
    ['Post base, adjustable', 'Hardware', 'ea', 14, 28, 'conc box lum'],
    ['Bull float 48 in', 'Tools', 'ea', 130, 240, 'conc tool'],
    ['Magnesium hand float', 'Tools', 'ea', 28, 55, 'conc box'],
    ['Steel finishing trowel 16 in', 'Tools', 'ea', 34, 68, 'conc box'],
    ['Edger and groover set', 'Tools', 'ea', 28, 55, 'conc box'],
    ['Concrete rake, come-along', 'Tools', 'ea', 58, 110, 'conc tool'],
  ]);

  add('drywall', [
    ['Drywall 1/2 in, 4x8', 'Panels', 'ea', 12, 20, 'dry box'],
    ['Drywall 1/2 in, 4x12', 'Panels', 'ea', 18, 30, 'dry box'],
    ['Drywall 5/8 in type X, 4x8', 'Panels', 'ea', 15, 25, 'dry box'],
    ['Moisture resistant board, 4x8', 'Panels', 'ea', 18, 30, 'dry box'],
    ['Cement board 1/2 in, 3x5', 'Panels', 'ea', 14, 24, 'dry box'],
    ['Steel stud 3-5/8 in, 10 ft', 'Panels', 'ea', 6, 11, 'dry'],
    ['Steel track 3-5/8 in, 10 ft', 'Panels', 'ea', 6, 11, 'dry'],
    ['Joint compound all purpose, 4.5 gal', 'Prep', 'ea', 16, 28, 'dry box'],
    ['Joint compound lightweight, 4.5 gal', 'Prep', 'ea', 17, 30, 'dry box'],
    ['Setting compound 90 min, 18 lb', 'Prep', 'bag', 14, 26, 'dry box'],
    ['Paper joint tape, 500 ft', 'Prep', 'roll', 6, 12, 'dry box'],
    ['Mesh joint tape, 300 ft', 'Prep', 'roll', 8, 15, 'dry box'],
    ['Corner bead 8 ft', 'Prep', 'ea', 3.5, 7, 'dry box'],
    ['Drywall screws 1-1/4 in, 5 lb', 'Fasteners', 'box', 18, 32, 'dry box'],
    ['Drywall screws 1-5/8 in, 5 lb', 'Fasteners', 'box', 20, 35, 'dry box'],
    ['Batt insulation R13, 3.5 in, bag', 'Panels', 'bag', 48, 85, 'dry box'],
    ['Batt insulation R19, 6.25 in, bag', 'Panels', 'bag', 58, 105, 'dry box'],
    ['Batt insulation R30, bag', 'Panels', 'bag', 62, 115, 'dry box'],
    ['Rigid foam 1 in, 4x8', 'Panels', 'ea', 18, 32, 'dry box'],
    ['Spray foam, 12 oz can', 'Sealants', 'ea', 7, 14, 'dry box'],
    ['Texture spray, 20 oz', 'Finish', 'ea', 11, 22, 'dry box'],
  ]);

  add('framing', [
    ['2x4x8 stud, SPF', 'Panels', 'ea', 3.2, 6, 'lum box'],
    ['2x4x92-5/8 precut stud', 'Panels', 'ea', 3.4, 6.5, 'lum box'],
    ['2x6x10, SPF', 'Panels', 'ea', 8, 15, 'lum box'],
    ['2x8x12, SYP', 'Panels', 'ea', 16, 28, 'lum box'],
    ['2x10x16, SYP', 'Panels', 'ea', 28, 50, 'lum box'],
    ['4x4x8 treated post', 'Panels', 'ea', 9, 17, 'lum box'],
    ['6x6x8 treated post', 'Panels', 'ea', 24, 44, 'lum box'],
    ['LVL 1-3/4 x 11-7/8, per ft', 'Panels', 'lf', 7, 13, 'lum'],
    ['OSB sheathing 7/16 in, 4x8', 'Panels', 'ea', 14, 26, 'lum box'],
    ['Plywood CDX 1/2 in, 4x8', 'Panels', 'ea', 24, 44, 'lum box'],
    ['Plywood 3/4 in tongue and groove, 4x8', 'Panels', 'ea', 38, 68, 'lum box'],
    ['House wrap 9x100 ft', 'Prep', 'roll', 145, 250, 'lum box roof'],
    ['Flashing tape 4 in x 75 ft', 'Prep', 'roll', 22, 42, 'lum box roof'],
    ['Joist hanger 2x8, 25 pk', 'Hardware', 'box', 32, 58, 'lum box'],
    ['Hurricane tie, 25 pk', 'Hardware', 'box', 26, 48, 'lum box'],
    ['Framing nails 3-1/4 in, 2000 ct', 'Fasteners', 'box', 48, 85, 'lum box'],
    ['Structural screws 4 in, 50 ct', 'Fasteners', 'box', 34, 62, 'lum box'],
    ['Deck boards composite, per lf', 'Panels', 'lf', 3.2, 7, 'lum box'],
    ['Deck screws 2-1/2 in, 5 lb', 'Fasteners', 'box', 26, 48, 'lum box'],
  ]);

  add('tools', [
    ['Utility knife blades, 100 ct', 'Tools', 'box', 14, 28, 'tool box'],
    ['Chalk line and chalk', 'Tools', 'ea', 14, 28, 'tool box'],
    ['Tape measure 25 ft', 'Tools', 'ea', 16, 34, 'tool box'],
    ['Speed square', 'Tools', 'ea', 9, 20, 'tool box'],
    ['Cordless drill and driver kit', 'Tools', 'ea', 165, 350, 'tool box'],
    ['Circular saw blade 7-1/4 in, 3 pk', 'Tools', 'pk', 24, 48, 'tool box'],
    ['Reciprocating blades, 10 pk', 'Tools', 'pk', 18, 38, 'tool box'],
    ['Diamond blade 7 in', 'Tools', 'ea', 28, 62, 'tool box conc'],
    ['Extension cord 12/3, 100 ft', 'Tools', 'ea', 68, 125, 'tool box elec'],
    ['Work light, LED 10000 lumen', 'Tools', 'ea', 58, 120, 'tool box'],
    ['Ladder, 24 ft extension', 'Tools', 'ea', 210, 420, 'tool box'],
    ['Ladder, 6 ft step fiberglass', 'Tools', 'ea', 95, 185, 'tool box'],
    ['Safety glasses, 12 pk', 'Tools', 'box', 18, 34, 'tool box'],
    ['Work gloves, 12 pk', 'Tools', 'box', 26, 52, 'tool box'],
    ['N95 respirators, 20 ct', 'Tools', 'box', 22, 42, 'tool box'],
    ['Contractor bags, 50 ct', 'Tools', 'box', 24, 45, 'tool box'],
    ['Shop vac, 12 gal', 'Tools', 'ea', 95, 185, 'tool box'],
    ['Generator, 5000W', 'Tools', 'ea', 480, 900, 'tool box northerntool'],
    ['Construction adhesive, 12 pk', 'Sealants', 'case', 38, 70, 'tool box'],
    ['Screws assorted bulk pack', 'Fasteners', 'box', 28, 55, 'tool box'],
  ]);

  add('pools', [
    ['Pool pump, variable speed 1.65 HP', 'Pumps', 'ea', 720, 1250, 'pool'],
    ['Pool pump, single speed 1 HP', 'Pumps', 'ea', 280, 520, 'pool box'],
    ['Booster pump for cleaner, 3/4 HP', 'Pumps', 'ea', 320, 560, 'pool'],
    ['Pump motor, 1.5 HP replacement', 'Pumps', 'ea', 240, 430, 'pool'],
    ['Pump basket and lid', 'Pumps', 'ea', 28, 58, 'pool'],
    ['Pump seal and gasket kit', 'Pumps', 'ea', 18, 38, 'pool'],
    ['Cartridge filter, 150 sq ft', 'Filters', 'ea', 340, 620, 'pool'],
    ['Cartridge filter element, 100 sq ft', 'Filters', 'ea', 78, 145, 'pool box'],
    ['DE filter, 48 sq ft', 'Filters', 'ea', 520, 900, 'pool'],
    ['Sand filter, 24 in with valve', 'Filters', 'ea', 420, 720, 'pool box'],
    ['Filter sand, 50 lb', 'Filters', 'bag', 14, 28, 'pool box'],
    ['DE powder, 25 lb', 'Filters', 'bag', 26, 48, 'pool'],
    ['Multiport valve, 6 position', 'Valves', 'ea', 130, 240, 'pool'],
    ['Pool heater, gas 400k BTU', 'Equipment', 'ea', 2200, 3600, 'pool'],
    ['Heat pump, pool 110k BTU', 'Equipment', 'ea', 2600, 4400, 'pool'],
    ['Salt chlorine generator', 'Equipment', 'ea', 850, 1550, 'pool'],
    ['Salt cell, replacement', 'Equipment', 'ea', 420, 780, 'pool'],
    ['Automation control panel', 'Controls', 'ea', 950, 1700, 'pool'],
    ['Chlorine tabs 3 in, 50 lb', 'Chemicals', 'bucket', 130, 230, 'pool box'],
    ['Liquid chlorine, 2x2.5 gal case', 'Chemicals', 'case', 16, 32, 'pool box'],
    ['Muriatic acid, 2x1 gal case', 'Chemicals', 'case', 18, 34, 'pool box'],
    ['Soda ash, 25 lb', 'Chemicals', 'bag', 32, 58, 'pool'],
    ['Calcium hardness increaser, 50 lb', 'Chemicals', 'bag', 48, 88, 'pool'],
    ['Cyanuric acid stabilizer, 25 lb', 'Chemicals', 'bag', 62, 115, 'pool'],
    ['Algaecide, 1 gal', 'Chemicals', 'ea', 34, 68, 'pool box'],
    ['Pool shock, 1 lb bags, 24 ct', 'Chemicals', 'case', 48, 92, 'pool box'],
    ['Diatomaceous earth alternative, 25 lb', 'Chemicals', 'bag', 38, 72, 'pool'],
    ['Vinyl liner, 20x40 overlap', 'Liner', 'ea', 850, 1600, 'pool'],
    ['Liner patch kit, underwater', 'Liner', 'ea', 18, 38, 'pool box'],
    ['Pool plaster mix, 100 lb', 'Liner', 'bag', 32, 58, 'pool'],
    ['Pebble finish aggregate, 50 lb', 'Liner', 'bag', 48, 88, 'pool'],
    ['Waterline tile, 6x6 pack', 'Tile', 'pk', 26, 52, 'pool tile'],
    ['Pool coping, precast per lf', 'Hardscape', 'lf', 11, 24, 'pool land'],
    ['Skimmer, complete', 'Drainage', 'ea', 78, 150, 'pool'],
    ['Main drain, dual VGB', 'Drainage', 'ea', 68, 130, 'pool'],
    ['Return fitting and eyeball', 'Fittings', 'ea', 8, 18, 'pool box'],
    ['PVC flex hose 2 in, 25 ft', 'Pipe', 'roll', 42, 78, 'pool'],
    ['Pool LED light, color 12V', 'Lighting', 'ea', 280, 520, 'pool'],
    ['Niche and conduit kit', 'Lighting', 'ea', 95, 180, 'pool'],
    ['Robotic pool cleaner', 'Tools', 'ea', 650, 1400, 'pool box'],
    ['Leaf rake and pole set', 'Tools', 'ea', 42, 85, 'pool box'],
    ['Test kit, drop reagent', 'Tools', 'ea', 28, 58, 'pool box'],
    ['Winter cover, 20x40', 'Tools', 'ea', 180, 340, 'pool box'],
    ['Safety cover, mesh custom', 'Tools', 'ea', 1800, 3200, 'pool'],
  ]);

  add('trim', [
    ['Base moulding, MDF 5-1/4 in, per lf', 'Trim', 'lf', 1.3, 2.8, 'mill box'],
    ['Base moulding, primed pine 5-1/4 in, per lf', 'Trim', 'lf', 1.9, 3.8, 'mill box'],
    ['Casing, MDF 3-1/2 in, per lf', 'Trim', 'lf', 1.1, 2.4, 'mill box'],
    ['Casing, colonial pine 2-1/4 in, per lf', 'Trim', 'lf', 1.2, 2.6, 'mill box'],
    ['Crown moulding, MDF 5 in, per lf', 'Trim', 'lf', 1.8, 3.6, 'mill box'],
    ['Crown moulding, poplar 5-1/4 in, per lf', 'Trim', 'lf', 3.2, 6.5, 'mill'],
    ['Shoe moulding, per lf', 'Trim', 'lf', 0.7, 1.6, 'mill box'],
    ['Quarter round, per lf', 'Trim', 'lf', 0.7, 1.6, 'mill box'],
    ['Chair rail, per lf', 'Trim', 'lf', 1.6, 3.4, 'mill box'],
    ['Panel moulding, per lf', 'Trim', 'lf', 1.4, 3.2, 'mill'],
    ['Shiplap, primed 8 in, per lf', 'Trim', 'lf', 2.2, 4.5, 'mill box'],
    ['Beadboard panel, 4x8', 'Panels', 'ea', 28, 55, 'mill box'],
    ['Stair tread, red oak 48 in', 'Trim', 'ea', 42, 85, 'mill box'],
    ['Stair riser, primed 48 in', 'Trim', 'ea', 14, 30, 'mill box'],
    ['Newel post, 3-1/2 in', 'Trim', 'ea', 95, 200, 'mill'],
    ['Baluster, wood 36 in', 'Trim', 'ea', 6, 14, 'mill box'],
    ['Handrail, oak per lf', 'Trim', 'lf', 8, 18, 'mill box'],
    ['Interior door, hollow core prehung 30 in', 'Doors', 'ea', 95, 185, 'mill box'],
    ['Interior door, solid core prehung 32 in', 'Doors', 'ea', 210, 420, 'mill box'],
    ['Bifold door, 24 in', 'Doors', 'ea', 68, 140, 'mill box'],
    ['Barn door kit with track', 'Doors', 'ea', 240, 480, 'mill box'],
    ['Exterior door, fiberglass prehung 36 in', 'Doors', 'ea', 420, 900, 'mill box'],
    ['Door casing kit, one side', 'Trim', 'ea', 24, 48, 'mill box'],
    ['Door hinges, 3-1/2 in, 3 pk', 'Hardware', 'pk', 9, 20, 'cab box'],
    ['Passage lever set', 'Hardware', 'ea', 22, 48, 'cab box'],
    ['Privacy lever set', 'Hardware', 'ea', 26, 55, 'cab box'],
    ['Deadbolt, single cylinder', 'Hardware', 'ea', 32, 72, 'cab box'],
    ['Door stop, 3 pk', 'Hardware', 'pk', 7, 15, 'box'],
    ['Window, vinyl double hung 36x48', 'Windows', 'ea', 280, 560, 'mill box'],
    ['Window trim kit, exterior', 'Trim', 'ea', 38, 78, 'mill box'],
    ['Finish nails 16 ga, 2-1/2 in, 2500 ct', 'Fasteners', 'box', 24, 48, 'box tool'],
    ['Brad nails 18 ga, 2 in, 5000 ct', 'Fasteners', 'box', 18, 38, 'box tool'],
    ['Construction adhesive for trim, 12 pk', 'Sealants', 'case', 38, 70, 'box'],
    ['Paintable caulk for trim, 12 pk', 'Sealants', 'case', 32, 58, 'paint box'],
    ['Wood filler, stainable 1 qt', 'Prep', 'ea', 12, 26, 'box paint'],
  ]);

  add('cabinets', [
    ['Base cabinet, shaker 24 in', 'Cabinets', 'ea', 180, 400, 'cab box'],
    ['Base cabinet, shaker 36 in', 'Cabinets', 'ea', 240, 520, 'cab box'],
    ['Wall cabinet, shaker 30x30', 'Cabinets', 'ea', 165, 360, 'cab box'],
    ['Sink base cabinet, 36 in', 'Cabinets', 'ea', 220, 480, 'cab box'],
    ['Pantry cabinet, 24x84', 'Cabinets', 'ea', 420, 880, 'cab box'],
    ['Drawer base, 3 drawer 18 in', 'Cabinets', 'ea', 230, 500, 'cab box'],
    ['Vanity cabinet, 36 in', 'Cabinets', 'ea', 260, 620, 'cab box'],
    ['Cabinet door, shaker replacement', 'Cabinets', 'ea', 28, 75, 'cab'],
    ['Drawer box, dovetail', 'Cabinets', 'ea', 34, 78, 'cab'],
    ['Toe kick, matching 8 ft', 'Cabinets', 'ea', 18, 42, 'cab box'],
    ['Crown for cabinets, per lf', 'Trim', 'lf', 4, 11, 'cab box'],
    ['Filler strip, 3x96', 'Cabinets', 'ea', 14, 34, 'cab box'],
    ['Finished end panel', 'Panels', 'ea', 38, 88, 'cab'],
    ['Plywood, birch 3/4 in 4x8', 'Panels', 'ea', 62, 120, 'cab lum box'],
    ['Melamine panel, 3/4 in 4x8', 'Panels', 'ea', 42, 85, 'cab'],
    ['Edge banding, 250 ft roll', 'Panels', 'roll', 28, 62, 'cab'],
    ['Soft-close hinge, 100 pk', 'Hardware', 'box', 78, 165, 'cab'],
    ['Soft-close hinge, 10 pk', 'Hardware', 'pk', 14, 32, 'cab box'],
    ['Undermount drawer slides 18 in, 10 pr', 'Hardware', 'box', 130, 280, 'cab'],
    ['Side-mount drawer slides 20 in, 10 pr', 'Hardware', 'box', 58, 125, 'cab box'],
    ['Cabinet pulls, 4 in, 25 pk', 'Hardware', 'box', 48, 120, 'cab box'],
    ['Cabinet knobs, 25 pk', 'Hardware', 'box', 38, 95, 'cab box'],
    ['Lazy susan, 28 in', 'Hardware', 'ea', 78, 170, 'cab box'],
    ['Pull-out trash, double bin', 'Hardware', 'ea', 95, 210, 'cab box'],
    ['Drawer organiser insert', 'Hardware', 'ea', 34, 78, 'cab box'],
    ['Shelf pins, 100 ct', 'Hardware', 'box', 8, 18, 'cab box'],
    ['Cabinet screws 2-1/2 in, 100 ct', 'Fasteners', 'box', 14, 30, 'cab box'],
    ['Pocket screws, 500 ct', 'Fasteners', 'box', 22, 45, 'box tool'],
    ['Under cabinet lighting, 4 pk', 'Lighting', 'case', 68, 145, 'cab box elec'],
    ['Cabinet touch-up kit', 'Finish', 'ea', 18, 42, 'cab'],
  ]);

  add('countertops', [
    ['Quartz slab, level 1 per sq ft', 'Stone', 'sqft', 32, 55, 'stone'],
    ['Quartz slab, level 3 per sq ft', 'Stone', 'sqft', 55, 95, 'stone'],
    ['Granite slab, level 1 per sq ft', 'Stone', 'sqft', 28, 50, 'stone'],
    ['Granite slab, exotic per sq ft', 'Stone', 'sqft', 60, 120, 'stone'],
    ['Marble slab, per sq ft', 'Stone', 'sqft', 55, 130, 'stone'],
    ['Porcelain slab, per sq ft', 'Stone', 'sqft', 45, 85, 'stone'],
    ['Butcher block, 8 ft', 'Panels', 'ea', 180, 420, 'box'],
    ['Laminate countertop, post-form per lf', 'Panels', 'lf', 18, 42, 'box'],
    ['Solid surface sheet, per sq ft', 'Stone', 'sqft', 26, 52, 'stone'],
    ['Undermount sink clips, 10 pk', 'Hardware', 'pk', 12, 28, 'stone'],
    ['Countertop support bracket, hidden', 'Hardware', 'ea', 22, 55, 'box cab'],
    ['Stone adhesive, color matched tube', 'Sealants', 'ea', 14, 32, 'stone'],
    ['Silicone, clear kitchen and bath, 12 pk', 'Sealants', 'case', 38, 72, 'box paint'],
    ['Stone sealer, 1 qt', 'Finish', 'ea', 24, 55, 'stone box'],
    ['Seam setter, suction', 'Tools', 'ea', 180, 380, 'stone'],
    ['Diamond polishing pads, 7 pc set', 'Tools', 'pk', 48, 110, 'stone tool'],
    ['Diamond blade for stone, 10 in', 'Tools', 'ea', 95, 220, 'stone tool'],
    ['Core bit, 1-3/8 in diamond', 'Tools', 'ea', 42, 95, 'stone tool'],
    ['Slab transport A-frame rack', 'Tools', 'ea', 420, 900, 'stone'],
    ['Suction cup lifters, pair', 'Tools', 'pr', 68, 150, 'stone tool'],
    ['Backsplash tile, subway per sq ft', 'Tile', 'sqft', 2.2, 6.5, 'tile box'],
    ['Backsplash mosaic sheet, 12x12', 'Tile', 'ea', 8, 22, 'tile box'],
    ['Thinset for stone, 50 lb', 'Sealants', 'bag', 18, 38, 'tile box'],
    ['Grout, unsanded 25 lb', 'Sealants', 'bag', 22, 45, 'tile box'],
    ['Edge profile, bullnose per lf', 'Stone', 'lf', 12, 28, 'stone'],
    ['Sink cutout and polish, per opening', 'Stone', 'ea', 95, 220, 'stone'],
    ['Cooktop cutout, per opening', 'Stone', 'ea', 85, 190, 'stone'],
  ]);

  add('flooring', [
    ['Luxury vinyl plank, per sq ft', 'Flooring', 'sqft', 1.8, 4.5, 'tile box'],
    ['Engineered hardwood, per sq ft', 'Flooring', 'sqft', 3.4, 8.5, 'tile box'],
    ['Solid oak flooring, per sq ft', 'Flooring', 'sqft', 4.2, 9.5, 'tile box mill'],
    ['Laminate flooring, per sq ft', 'Flooring', 'sqft', 1.3, 3.4, 'tile box'],
    ['Carpet, per sq yd', 'Flooring', 'sqyd', 12, 34, 'box'],
    ['Carpet pad, per sq yd', 'Flooring', 'sqyd', 4, 9, 'box'],
    ['Porcelain tile 12x24, per sq ft', 'Tile', 'sqft', 1.8, 5.5, 'tile box'],
    ['Ceramic tile 12x12, per sq ft', 'Tile', 'sqft', 1.1, 3.2, 'tile box'],
    ['Wood-look plank tile, per sq ft', 'Tile', 'sqft', 2.4, 6, 'tile box'],
    ['Mosaic tile sheet, 12x12', 'Tile', 'ea', 7, 24, 'tile box'],
    ['Large format tile 24x48, per sq ft', 'Tile', 'sqft', 4, 11, 'tile'],
    ['Tile trim, Schluter edge 8 ft', 'Trim', 'ea', 18, 42, 'tile box'],
    ['Transition strip, 3 ft', 'Trim', 'ea', 12, 30, 'tile box'],
    ['Thinset, modified 50 lb', 'Sealants', 'bag', 16, 34, 'tile box'],
    ['Large format thinset, 50 lb', 'Sealants', 'bag', 24, 48, 'tile box'],
    ['Grout, sanded 25 lb', 'Sealants', 'bag', 20, 42, 'tile box'],
    ['Epoxy grout, 1 gal kit', 'Sealants', 'ea', 62, 130, 'tile'],
    ['Grout sealer, 1 qt', 'Finish', 'ea', 18, 40, 'tile box'],
    ['Flooring adhesive, 4 gal', 'Sealants', 'ea', 68, 140, 'tile box'],
    ['Underlayment foam, 100 sq ft roll', 'Prep', 'roll', 22, 48, 'tile box'],
    ['Cork underlayment, 100 sq ft', 'Prep', 'roll', 55, 110, 'tile'],
    ['Uncoupling membrane, 150 sq ft', 'Prep', 'roll', 130, 260, 'tile box'],
    ['Waterproofing membrane, 1 gal', 'Prep', 'ea', 48, 98, 'tile box'],
    ['Self-levelling compound, 50 lb', 'Prep', 'bag', 32, 62, 'tile box'],
    ['Backer board 1/2 in, 3x5', 'Panels', 'ea', 13, 26, 'tile box dry'],
    ['Backer board screws, 200 ct', 'Fasteners', 'box', 16, 34, 'tile box'],
    ['Tile spacers, 500 ct', 'Tools', 'bag', 8, 18, 'tile box'],
    ['Levelling clips and wedges, 500 ct', 'Tools', 'box', 42, 88, 'tile box'],
    ['Tile saw, 7 in wet', 'Tools', 'ea', 180, 420, 'tile box tool'],
    ['Notched trowel set', 'Tools', 'ea', 22, 48, 'tile box'],
    ['Grout float and sponges', 'Tools', 'ea', 18, 40, 'tile box'],
    ['Knee pads, gel', 'Tools', 'pr', 24, 55, 'box tool'],
    ['Stair nose, per lf', 'Trim', 'lf', 12, 30, 'tile box'],
    ['Baseboard for flooring, per lf', 'Trim', 'lf', 1.3, 3, 'mill box'],
  ]);

  add('general', [
    ['Dumpster, 20 yd haul', 'Prep', 'ea', 420, 780, 'box'],
    ['Portable toilet, monthly', 'Prep', 'ea', 130, 260, 'box'],
    ['Temporary fence panel, 6x12', 'Prep', 'ea', 78, 160, 'tool'],
    ['Construction heater, propane', 'Tools', 'ea', 130, 290, 'box tool'],
    ['Dehumidifier, jobsite', 'Tools', 'ea', 280, 620, 'tool box'],
    ['Air scrubber with HEPA', 'Tools', 'ea', 420, 850, 'tool'],
    ['Poly sheeting 6 mil, 20x100', 'Prep', 'roll', 62, 125, 'box'],
    ['Zip wall dust barrier kit', 'Prep', 'ea', 48, 110, 'box tool'],
    ['Floor protection board, 38 in x 100 ft', 'Prep', 'roll', 55, 120, 'box'],
    ['Ram board equivalent, per roll', 'Prep', 'roll', 55, 115, 'box'],
    ['Hard hats, 4 pk', 'Tools', 'pk', 38, 78, 'tool box'],
    ['Hi-vis vests, 5 pk', 'Tools', 'pk', 26, 55, 'tool box'],
    ['Fall protection harness kit', 'Tools', 'ea', 130, 290, 'tool box'],
    ['First aid kit, 50 person', 'Tools', 'ea', 42, 95, 'tool box'],
    ['Fire extinguisher, 10 lb ABC', 'Tools', 'ea', 58, 125, 'tool box'],
    ['Jobsite sign and permit box', 'Prep', 'ea', 28, 68, 'box'],
    ['Wheelbarrow, 6 cu ft', 'Tools', 'ea', 95, 190, 'box tool'],
    ['Mixing tub, 20 gal', 'Tools', 'ea', 18, 38, 'box'],
    ['Ladder jacks and plank', 'Tools', 'ea', 180, 390, 'tool box'],
    ['Scaffold frame set, 5x5', 'Tools', 'ea', 130, 290, 'tool box'],
    ['Job box, 48 in lockable', 'Tools', 'ea', 280, 620, 'tool box'],
    ['Broom and shovel set', 'Tools', 'ea', 34, 72, 'box'],
    ['Shop rags, 25 lb box', 'Tools', 'box', 34, 68, 'box tool'],
    ['Layout paint, 12 pk', 'Tools', 'case', 42, 85, 'box tool'],
    ['Chalk refill, 5 lb', 'Tools', 'ea', 14, 30, 'box tool'],
  ]);

  SP.CATALOG = C;

  /* Which categories have a photo sitting in assets/materials/. Same deal
     as the supplier logos: an explicit list, so nothing is requested until
     the file is actually there and a card falls back to its drawn icon
     rather than a broken image. The filename is the category lowercased —
     Underlayment becomes underlayment.jpg. */
  SP.CATIMG = ''.split(' ').filter(Boolean);

  /* One place that turns whatever the contractor typed into Settings into a
     shelf. "Interior design" is flooring and tile, "general contractor" is
     the site and safety kit, and a pool builder is not a plumber even
     though half their list is pipe. A trade we do not recognise gets the
     whole catalog rather than an empty shop. */
  var TRADE_WORDS = [
    ['pools', ['pool', 'spa', 'hot tub']],
    ['countertops', ['countertop', 'counter top', 'granite', 'quartz', 'stone', 'surface']],
    ['cabinets', ['cabinet', 'millwork shop', 'joinery']],
    ['flooring', ['floor', 'tile', 'interior design', 'interior', 'design', 'carpet']],
    ['trim', ['trim', 'finish carpentry', 'carpentry', 'carpenter', 'molding', 'moulding', 'door', 'window']],
    ['roofing', ['roof', 'gutter', 'siding']],
    ['plumbing', ['plumb', 'drain', 'septic']],
    ['electrical', ['electric', 'solar', 'low voltage']],
    ['hvac', ['hvac', 'heating', 'air condition', 'air', 'heat', 'mechanical', 'refrigeration']],
    ['painting', ['paint', 'stain', 'drywall finish']],
    ['landscaping', ['landscap', 'lawn', 'irrigation', 'hardscape', 'yard', 'tree', 'garden']],
    ['concrete', ['concrete', 'mason', 'foundation', 'paving', 'driveway']],
    ['drywall', ['drywall', 'insulation', 'plaster']],
    ['framing', ['framing', 'lumber', 'deck', 'fence', 'structural']],
    ['general', ['general contract', 'general', 'remodel', 'renovation', 'construction', 'builder', 'handyman', 'restoration']],
  ];
  SP.tradeKey = function (trade) {
    var t = String(trade || '').toLowerCase();
    if (!t) return '';
    var hit = TRADE_WORDS.filter(function (r) {
      return r[1].some(function (w) { return t.indexOf(w) >= 0; });
    })[0];
    return hit ? hit[0] : '';
  };
  SP.catalogForTrade = function (trade) {
    var key = SP.tradeKey(trade);
    return key ? C.filter(function (x) { return x.trade === key; }) : C;
  };
  SP.trades = function () {
    var seen = {}; C.forEach(function (x) { seen[x.trade] = (seen[x.trade] || 0) + 1; });
    return seen;
  };
})();
